### PR TITLE
Feature: init singer.metrics usage

### PR DESCRIPTION
**Pull request by AlexanderMann**
# Motivation

https://github.com/datamill-co/target-postgres/issues/75

## Notes

Whereas the `tap`s for SQL _know_ which table they are persisting to, our `stream`s are potentially nested. For this reason, we include the following tags:

- `path`: `tuple` of `string`s representing the denested path to a given table
- `table`: optional `string` representing the remote table we are dealing with
- `schema`: `string` representing the remote schema we're dealing with
- `database`: `string` representing the remote database we're dealing with

## Testing

Output provided by the CCI tests:

```
INFO METRIC: {"type": "timer", "metric": "job_duration", "value": 0.013872385025024414, "tags": {"job_type": "upsert_table_schema", "path": ["stargazers"], "database": "target_postgres_test", "schema": "public", "table": "stargazers", "status": "succeeded"}}
INFO Writing table batch with 18 rows for `('stargazers',)`...
INFO METRIC: {"type": "timer", "metric": "job_duration", "value": 0.011026144027709961, "tags": {"job_type": "upsert_table_schema", "path": ["tmp_c85777c0_12cd_41a0_ad96_089ea9418713"], "database": "target_postgres_test", "schema": "public", "table": "tmp_c85777c0_12cd_41a0_ad96_089ea9418713", "status": "succeeded"}}
INFO METRIC: {"type": "counter", "metric": "record_count", "value": 18, "tags": {"count_type": "table_rows_persisted", "path": ["stargazers"], "database": "target_postgres_test", "schema": "public", "table": "stargazers"}}
INFO METRIC: {"type": "timer", "metric": "job_duration", "value": 0.03966832160949707, "tags": {"job_type": "table", "path": ["stargazers"], "database": "target_postgres_test", "schema": "public", "table": "stargazers", "status": "succeeded"}}
INFO METRIC: {"type": "counter", "metric": "record_count", "value": 18, "tags": {"count_type": "batch_rows_persisted", "path": ["stargazers"], "database": "target_postgres_test", "schema": "public"}}
INFO METRIC: {"type": "timer", "metric": "job_duration", "value": 0.041277408599853516, "tags": {"job_type": "batch", "path": ["stargazers"], "database": "target_postgres_test", "schema": "public", "status": "succeeded"}}
...
```

## Suggested Musical Pairing
https://soundcloud.com/10cc-official/art-for-arts-sake-album?in=drunken-ambassador/sets/interval

### CODE REVIEW

**Comment by awm33** [comment]
@AlexanderMann Why can't we know the table name for row counts and have to use paths? Even nested arrays eventually become tables. We place them in a table when we merge the tmp table or the current batch size for a full-table rep.

**Comment by AlexanderMann** [comment]
@awm33 I put in place both the path and the table:

```
{"path": ["pull_requests"], "database": "target_postgres_test", "schema": "public", "table": "pull_requests"}
```

For the top level stream we can't (necessarily) have a table name since that's cumulative inserts from all of the various nested objects. We could put in place a `stream` tag as well? Personally I think _more_ tags than fewer are useful for slicing metrics up, but that's just my experience building observability and monitoring systems.

**Comment by AlexanderMann** [comment]
@awm33 I redact my previous comment. The `stream` name is a little bit harder to get in place for this. We don't pass that information down into `SQLBase` presently (I think that's actually one of the refactor things we had wanted to do) and to get it down in there would be a bit of work.

For the time being, I'd vote that we _don't_ include the `stream` tag, but if we decide that it's actually more useful to have (etc.) I can bite that off as a part of this work.

**Comment by awm33** [comment]
@AlexanderMann Ok that may make sense then. I think what we'll probably want, which are aggregates, are for a given run, or over period of time, row counts per table in the data warehouse. It looks like the reverse is possible too given the path?

**Comment by AlexanderMann** [comment]
@awm33 back to you!

**Comment by awm33** [comment]
@AlexanderMann So beautiful 😍 . Imma query the crap out of these metrics once we start running this in prod.

**Pull request merged**
